[package]
name = "sven_coop_hook"
version = "0.1.0"
authors = ["rkr35"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = 'unwind'

[profile.release]
panic = 'unwind'
lto = 'fat'
codegen-units = 1
debug = 0

[dependencies]
log = "0.4"
simplelog = "0.7"
winapi = { version = "0.3", features = [
    "consoleapi",
    "minwindef",
    "libloaderapi",
    "processthreadsapi",
    "wincon",
    "winnt",
    "winuser",
]}