[package]
name = "sven_coop_hook"
version = "0.1.0"
authors = ["Royce"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
